# Configuration file for the RAG system
# Copy this to config.py and update with your actual values

import os
from typing import Optional

class Config:
    """Application configuration."""

    # API Keys
    GROQ_API_KEY: Optional[str] = os.getenv("GROQ_API_KEY")
    QDRANT_API_KEY: Optional[str] = os.getenv("QDRANT_API_KEY")
    QDRANT_URL: Optional[str] = os.getenv("QDRANT_URL")
    GEMINI_API_KEY: Optional[str] = os.getenv("GEMINI_API_KEY")

    # LLM settings
    # Provider can be: 'google' (Gemini via langchain_google_genai) or 'groq' (Groq via langchain_groq)
    PROVIDER: str = os.getenv("PROVIDER", "google")
    MODEL_NAME: str = os.getenv("MODEL_NAME", "gemini-2.5-pro")
    EMBEDDING_MODEL: str = "sentence-transformers/all-MiniLM-L6-v2"

    # Collection names
    SYLLABUS_COLLECTION: str = "syllabus"
    REFERENCE_COLLECTION: str = "references"

    # Chunk settings
    SYLLABUS_CHUNK_SIZE: int = 500
    REFERENCE_CHUNK_SIZE: int = 1000
    CHUNK_OVERLAP: int = 100

    # Search settings
    DEFAULT_K_DENSE: int = 8
    DEFAULT_K_SPARSE: int = 24
    DEFAULT_K_FINAL: int = 10

    # File paths
    UPLOAD_FOLDER: str = "uploads"
    ASSETS_FOLDER: str = "assets"
    DARK_THEME_CSS: str = "assets/dark-theme.css"

    # Marp settings
    MARP_CONFIG = {
        "theme": "uncover",
        "class": "invert",
        "paginate": True,
        "backgroundColor": "#1a1a1a",
        "color": "#ffffff",
        "header": "'Study Materials'",
        "footer": "'Generated by AI Assistant'",
        "size": "16:9",
        "width": 1280,
        "height": 720
    }

# Global config instance
config = Config()
